[tool.poetry]
name = "automl"
version = "0.1.0"
description = ""
authors = ["whiscashexe <132351181+whiscashexe@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
pandas = "^2.2.1"
scikit-learn = "^1.4.1.post1"
lightgbm = "^4.3.0"
japanize-matplotlib = "^1.1.3"
matplotlib = "^3.8.4"
seaborn = "^0.13.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
